### ISSUE TITLE
Don't prepare statements unless explicitly specified

### ISSUE THREAD

**Issue by mewa** [trinodb/trino-python-client#149]
This is linked to #148 but since it explores a different/wider aspect of this issue, I opted for creating another issue.

The root cause in #148 is that statements are prepared, which combined with a large number of values results in too large header sizes.

As I explored it, it got me thinking about whether we should be preparing each and every query before executing it. Especially since currently it seems everything is happening implicitly, without the knowledge of the user. Any thoughts?

**Comment by hashhar** [comment]
If I am reading the code correctly the prepared statements path is only used when `params` are provided to `execute`. If not plain SQL is sent as it is.

Are you observing different behaviour?

**Comment by mewa** [comment]
I had to dig into the stack traces since we're not calling `execute` directly, but yes, the `params` are provided.

For context, we're using:
1. pandas - which in turn [calls](https://github.com/pandas-dev/pandas/blob/master/pandas/io/sql.py#L835-L848) sqlalchemy
1. sqlalchemy - which [relies](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/engine/base.py#L1276-L1278) on [sqlalchemy-trino](https://github.com/dungdm93/sqlalchemy-trino) dialect to communicate with Trino
1. finally, [sqlalchemy-trino](https://github.com/dungdm93/sqlalchemy-trino) then [calls](https://github.com/dungdm93/sqlalchemy-trino/blob/master/sqlalchemy_trino/dialect.py#L268-L275) the Trino client

I think the issue here is that the client is doing more than it's asked for. In my opinion, deciding which statement should be prepared (or not) is the end-user's responsibility.

**Comment by hashhar** [comment]
There is no way today (or before the PR which added prepared statements support) to be able to pass parameters to a query without using prepared statements.

If you want to avoid prepared statements you need to stop passing params by constructing the SQL as a string and then calling `cursor.execute(sql)` instead of `cursor.execute(sql, params)`.

I'm not sure if there's a way to have both:

1. Ability for client to handle params.
2. Not use prepared statements when params are passed.

What solution are you suggesting?

**Comment by hashhar** [comment]
Other than doing client side "prepare" (like `mogrify` in `psycopg2`) there are no solutions and we'd rather not go there.

Closing for now. Feel free to re-open if someone has ideas of how to do this safely.
