### ISSUE TITLE
"CALL system.sync_partition_metadata" query not working

### ISSUE THREAD

**Issue by yaelsteinberger** [trinodb/trino-python-client#56]
As per your instructions I was successfully able to query and receive table's data from presto.
I wanted to sync my table's partitions with the following query: 
**"CALL system.sync_partition_metadata(schema_name => 'my_schema', table_name => 'my_table', mode => 'full')"**
However, it wasn't successful, (haven't got any errors though) - Same query is working fine in presto's CLI. 

**This is my code:**
 ```
schema = 'my_schema'
table = 'my_table'
query = f"CALL system.sync_partition_metadata(" \
                                 f"schema_name => '{schema}', table_name => '{table}', " \
                                 f"mode => 'FULL')"

conn = presto.dbapi.connect(
            host='presto.default.svc.cluster.local',
            port=8080,
            user='0',
            catalog='hive',
            schema=schema,
        )
cur = conn.cursor()
cur.execute(query)
```

After that I checked using the query: ```SELECT * from "my_table$partitions"```
But, the partitions list hasn't been updated with the new ones I've added to my bucket.

Am I doing something wrong?

**Comment by findepi** [comment]
> ```
> cur = conn.cursor()
> cur.execute(query)
> ```

This submits the query but is not sufficient to make the query run, because of https://github.com/prestosql/presto/commit/568449b8d058ed8281cc5277bb53902fd044cad7
You need to check the results of the query using `cur.fetchall()`.
In fact, you probably want to do check the results anyway, to e.g. ensure your query does not fail.

HTH.
Let me close this as answered. Please reopen if this still doens't work.

**Comment by amitds1997** [comment]
Since it's been more than 4 months and the README has been updated, closing this.
